name: CMake

on:
  push:
    branches: [ '*' ]

env:
  BUILD_TYPE: Release

jobs:
  build-ubuntu-release:
    runs-on: ubuntu-latest

    env:
      VCPKG_DISABLE_METRICS: 1
      VCPKG_ROOT: ${{ github.workspace }}/vcpkg

    steps:
    - uses: actions/checkout@v3
    
    # I will change this to use matrix.os with an if statement in the future. //shrug
    - name: Download Packages
      run: sudo apt update && sudo apt install cmake autoconf libtool libx11-dev libsfml-dev xorg-dev libopengl-dev mesa-common-dev libudev-dev libopenal-dev libvorbis-dev libflac-dev libncurses-dev libxrandr-dev libxi-dev libgl1-mesa-dev libevdev-dev
      shell: bash

    - name: Copy libevdev to Directory
      run: |
        cd /usr/include/libevdev-1.0
        sudo mv libevdev ../

    - name: Set up VCPKG
      uses: lukka/run-vcpkg@v10
      with:
        vcpkgGitCommitId: f3a39f1aaffe48b1190df69aab3a8657f91b632a

    - name: Set up Private SSH Key 
      uses: webfactory/ssh-agent@v0.7.0
      with:
        ssh-private-key: ${{ secrets.SSH_KEY }}

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
      
  build-windows-release:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up VCPKG
      uses: lukka/run-vcpkg@v10
      with:
        vcpkgGitCommitId: f3a39f1aaffe48b1190df69aab3a8657f91b632a

    - name: Set up Private SSH Key 
      uses: webfactory/ssh-agent@v0.7.0
      with:
        ssh-private-key: ${{ secrets.SSH_KEY }}

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
      
#  build-macos-release:
#    runs-on: macos-latest
#
#    steps:
#    - uses: actions/checkout@v3
#   
#    - name: Download Packages
#      run: brew install pkg-config
#
#    - name: Set up VCPKG
#      uses: lukka/run-vcpkg@v10
#        with:
#           vcpkgGitCommitId: f3a39f1aaffe48b1190df69aab3a8657f91b632a
#
#    - name: Set up Private SSH Key 
#      uses: webfactory/ssh-agent@v0.7.0
#      with:
#        ssh-private-key: ${{ secrets.SSH_KEY }}
#
#    - name: Configure CMake
#      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
#
#    - name: Build
#      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
